# Generated by Django 4.1 on 2023-10-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('enderco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Numero')),
                ('telefone', models.CharField(max_length=9, verbose_name='Telefone')),
            ],
        ),
    ]
