# Generated by Django 4.1 on 2023-10-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descriacao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='enderco',
            new_name='endereco',
        ),
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='E-mail'),
        ),
    ]
